name: Front Rowe
favicon: null
layout_spectrum: 0.6694772
typography_spectrum: 0.4291737
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Traveler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9709697382058948
  lightness: 0.272344
  saturation: 0.6155143
  rhythmicContrast: 0.391231
purpose: []
