cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6155143
  brandStrength: 0.9709697382058948
  lightness: 0.272344
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.391231
typography_spectrum: 0.4291737
layout_spectrum: 0.6694772
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Front Rowe
